"""
BearishTaUsdcWethBase Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import BearishTaUsdcWethBaseStrategy
except ImportError:
    from strategy import BearishTaUsdcWethBaseStrategy

__all__ = [
    "BearishTaUsdcWethBaseStrategy",
]
